### PR TITLE
Multiple enhancements

### PR DESCRIPTION
**Pull request by kodaman2**
Initial pull request was #121 

Fixed py2 issue. and fixed tox.ini file for linux unittesting with tox.

### CODE REVIEW

**Comment by dmroeder** [comment]
I had another thought, the UDT class members are lower case.  While this is more pythonic, and probably ideal, the rest of the project is not.  As you know, I considered making the change to be more pythonic,  I ultimately decided (for better or worse) to keep it the way it had been so as not to disturb existing users.

**Comment by kodaman2** [comment]
> I had another thought, the UDT class members are lower case. While this is more pythonic, and probably ideal, the rest of the project is not. As you know, I considered making the change to be more pythonic, I ultimately decided (for better or worse) to keep it the way it had been so as not to disturb existing users.

udt classs has been fixed.

**Comment by kodaman2** [comment]
> I had another thought, the UDT class members are lower case. While this is more pythonic, and probably ideal, the rest of the project is not. As you know, I considered making the change to be more pythonic, I ultimately decided (for better or worse) to keep it the way it had been so as not to disturb existing users.

UDT class has been changed to lowercase, and fixed UDT references. py2 and py3 still passing  current unittests. : )

**Comment by jprogin-i3** [comment]
> We just need to figure out, how to test new enhancements.

1. You can add a new tag in the PLC which will be an array of structures. This structure type should have at least one field of another structure type. Then check that the **GetTagList** discover all fields of the array cells recursively.

1. For the **Read** enhancement, you can test it by calling the **Read** with an array containing 300 times the same tag path; because the request block size should not exceed 512 bytes and because the request is containing the tags names, this limit will be exceeded with the 300 tags. The changes I did will split the read into chunks when needed (with 300 tags it will be needed) and the results will be reassembled in a single response.

**Comment by dmroeder** [comment]
Okay @jprogin , I did a little testing on this.  First off, on its face, these are good improvements and I thank you for your effort.  However there are some flaws that need to be resolved.  I will say, I have worked on both of these features to some degree though never committed to any of the results that I came up with. 

**Bulk Reads:**
Great idea, I worked on this one a while back, but got too busy to follow through.  The tricky part here has to do with both the request and reply.  You cannot simply rely on the length of the tag name or the number of tags to decide how many go into the request because the data type matters.  Consider a few scenarios:

- A bunch of really short tag names
- A bunch of really long tag names
- A bunch of really long tag names that are program scoped

The number of tags that we decide that can go into a "bulk read" will go down with each of the scenarios I described above because the tag name will take up increasingly more space in the request packet.   What we also have to take into accout is the data type.  Just because you can fit _n_ of tag names into the request, doesn't mean they will fit into the reply.  SINT's are 1 byte, STRING's are 88.

If I create a bunch of tags that are of the DINT data type, it seems to work well, if they are the STRING data type, it fails because "partial transfer" needs to be handled.   More data is being asked for than can fit in the reply

Also, another curve ball is that the connection size can vary depending on the hardware/firmware.   Some controllers support a max connection size of 511 bytes, others support up to 4000.  I don't think this is being considered.

**Recursive Tag List**
First thing I noticed:  I made some recent changes to minimize the number of exceptions raised.  For example, if you try to connect to a PLC that doesn't exist, Response class will be returned with the socket exception as the status.  I'm guessing the enhancements in this branch were made prior to me pushing those changes because GetTagList no longer handles failed connections this way.

The other thing that I notice is that there is an optimization problem that is causing more traffic than necessary.  It doesn't seem that there is much consideration being made as to whether the makeup of a data type has already been requested.  For example, I made a program with 6 unique tags that were TIMER data type.  Then I made a UDT that has 2 members which were also the TIMER data type.  I made one instance of the UDT.  If you request the tag list, you will see that the TIMER data type makeup was requested several times when it should have only been requested once.

For what it's worth, I'm impressed that you are able to get in there and work on this.  I look forward to further discussion.

**Comment by kyle-github** [comment]
Just a quick note: for almost all "modern" Control Logix PLCs (and possibly the Compact Logix models), using the Forward Open Extended packet, you can negotiate a 4002 byte packet instead of 544 bytes.   

I have found that this makes the multiple-request CIP command much more useful!

**Comment by dmroeder** [comment]
> Just a quick note: for almost all "modern" Control Logix PLCs (and possibly the Compact Logix models), using the Forward Open Extended packet, you can negotiate a 4002 byte packet instead of 544 bytes.
> 
> I have found that this makes the multiple-request CIP command much more useful!

For sure, however, I want to support all Logix based controllers, so I need to support all the connection sizes.  Even if someone decides to set the connection size to 2000 bytes instead of 4000.

**Comment by jprogin-i3** [comment]
Sorry @dmroeder, but I don't know how to commit in this pull request... 

Below a patch that should solve the problems you mentioned previously:

[corrections.patch.txt](https://github.com/dmroeder/pylogix/files/4438384/corrections.patch.txt)

**Comment by kodaman2** [comment]
> Sorry @dmroeder, but I don't know how to commit in this pull request...
> 
> Below a patch that should solve the problems you mentioned previously:
> 
> [corrections.patch.txt](https://github.com/dmroeder/pylogix/files/4438384/corrections.patch.txt)

I know is a pain, I couldn't figure out how to sanely commit to your earlier PR either. If is easier for you, we can close this PR and you can start a new one from your earlier branch, but see what I've changed UDT member names to upper case, and the 4 lines that Dustin mentioned you should be able to see in the commits.

> First thing I noticed: I made some recent changes to minimize the number of exceptions raised. For example, if you try to connect to a PLC that doesn't exist, Response class will be returned with the socket exception as the status. I'm guessing the enhancements in this branch were made prior to me pushing those changes because GetTagList no longer handles failed connections this way.

@dmroeder he's using the latest branch the one I commited after the docs changes. If response class is not being returned in something then something is obviously wrong, but nevertheless he's using latest master branch. You can see version is 0.6.6 and updated changelog in his commit.

**Comment by jprogin-i3** [comment]
@kodaman2 I have worked on the branch **jprogin-i3-recursive_tags**. You can simply check it out, apply the attached patch and commit the changes.

@dmroeder I have added a check in the **GetTagList** to support the special exception cases.

I have added a **StringEncoding** field into the PLC class: this was needed to supports the **latin-1** encoded strings that I have encountered in my PLC...

**Comment by schallerala** [comment]
Any updates on this one? @kodaman2

**Comment by dmroeder** [comment]
> Any updates on this one? @kodaman2

This is on my plate.  I started to test last night, just not enough time in a day.

**Comment by dmroeder** [comment]
@jprogin-i3, I _finally_ got a little time to do some testing.  There is still an issue where where too many requests are being made with GetTagList, though I now understand why.  Only UDT's are being stored in the new UDT dict, I think any struct should be included (TIMER for example).

I had made a simple program with 2 timers plus an instance of a UDT that included 2 timers.  The makeup of a TIMER was requested 3 times when it really only should have been requested once.  Here is a patch that fixes it, while I don't think it breaks anything you have done, I would like  you to verify before I push it out.

[0001-Fixed-excessive-requests-when-getting-tag-list.patch.txt](https://github.com/dmroeder/pylogix/files/4465768/0001-Fixed-excessive-requests-when-getting-tag-list.patch.txt)

I also made some changes to the LgxTag and UDT classes:

[0001-Updated-UDT-and-LgxTag-classes.patch.txt](https://github.com/dmroeder/pylogix/files/4465774/0001-Updated-UDT-and-LgxTag-classes.patch.txt)

Lastly, would it make sense to apply your .StringEncoding throughout the entire project?

I look forward to hearing your thoughts!

**Comment by jprogin** [comment]
Thanks for the job. I’m in holidays for the next week and will check when back to the job.

Happy Eastern 

Jacques

**Comment by jprogin-i3** [comment]
@dmroeder the patch works fine and I think you can commit it. Thanks for enhancements!

Then I don't think we can replace all _utf-8_ occurrences in the project with the **StringEncoding** feature. I suppose that the variable name and other CIP internal strings could not be encoded differently... In that way, I think the **StringEncoding** should only apply to the content of the string user variables.

Is there still pending issues with the pull request?

**Comment by dmroeder** [comment]
@jprogin-i3 since everything worked for you, I'll commit the changes I made and pull it when I get a bit.

**Comment by jprogin-i3** [comment]
@dmroeder Thanks for the merge. Did you planned to release a version soon?

**Comment by dmroeder** [comment]
I will tag it and put the latest up on pypi this afternoon.

**Comment by dmroeder** [comment]
It's up there now

**Pull request merged**
