### PR TITLE
Increase Discovery Cohesion

### PR DESCRIPTION
**Pull request by William-Brumble**
## Short description of change

Software architecture change to reduce unnecessary coupling and increase class cohesion.

lgx_comm.py
Add the discovery network-level business logic previously in the PLC class to the Connection class.
Decided to avoid the unnecessary import of Device by passing in procedural parameter to the interface.

eip.py
Remove the socket module coupling and increase PLC class cohesion by moving the network-level business 
logic to the Connection class, where it usually takes place.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **docs/CONTRIBUTING.md** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?

lgx_comm.py
Add the discovery network-level business logic previously in the PLC class to the Connection class.
Decided to avoid the unnecessary import of Device by passing in procedural parameter to the interface.

eip.py
Remove the socket module coupling and increase PLC class cohesion by moving the network-level business 
logic to the Connection class, where it usually takes place.

## What does it fix/add?

Software architecture change to reduce unnecessary coupling and increase class cohesion.

## Test Configuration

I ran example 20_discover_devices without issue.

- PLC Model
	1756-L84E/B
- PLC Firmware
	32.014
- pylogix version
	0.8.6
- python version
	3.7.7
- OS type and version
	Winblows Server 2016 Version 10.0.14393 Build 14393

### CODE REVIEW

**Comment by TheFern2** [comment]
Thanks for the PR, Is this really a breaking change? Are any tests failing with tox?

**Comment by William-Brumble** [comment]
Not really breaking, but checked that box due to functionality (routing) change.

Took be a bit to get internet/system setup with everything needed to run all Python versions.

Python versions:
3.10.6
3.8.10
3.7.9
3.5.4
3.4.4
2.7.18

Result:
  py27: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py37: commands succeeded
  py38: commands succeeded
  py310: commands succeeded
  congratulations :)

I needed to add the tags: Nemesis array, and Str1-50, to the program.
The test cases required them but they were missing from the clx setup files.
The files need to be updated to include those tags.

But the video and readme were very descriptive in getting a test environment setup.

**Comment by dmroeder** [comment]
Nice work.  I'll update the setup files

**Comment by William-Brumble** [comment]
I went ahead and updated the controller scope tags for you guys.

**Comment by TheFern2** [comment]
Good work! When I run tox, I usually just run latest major versions on 2 and 3. That way you don't have to install every single python version.

**Pull request merged**
