### PR TITLE
Update vendor list

### PR DESCRIPTION
**Pull request by PhilippHaefele**
## Short description of change

Updated vendors from a vid file that was kindly provided to me from ODVA.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. => Sorry i do not have a micro 800, but changes shouldn't break any test

## What is the change?

I wrote a small python script to read the ODVA file and output in a predefined format, so i can update vendors in different tools.
To preserve obsolete vendors, i issue a list of them separately.

Some company names have special UTF-8 characters like ü, ä, ç, ã and ）/ U+FF09 and as this lib does have a python 2 support i replace them with matching replacement values (e.g. `ü` => `ue`).

There were some Reserved entries in the list and as they do not have any informational value i removed them.

## What does it fix/add?

Updated vendor list

## Test Configuration

as mentioned above i couldn't do a test as i do not have a micro 800

### CODE REVIEW

**Comment by TheFern2** [comment]
I guess it doesn't matter much for the vendors list because it probably hasn't changed in either repo but just fyi, this fork is from pylogix2  (Daniel) not pylogix.

So in the future if you want to make more PRs please fork this repo or add this repo as upstream to keep up with the latest changes.

**Comment by dmroeder** [comment]
> I guess it doesn't matter much for the vendors list because it probably hasn't changed in either repo but just fyi, this fork is from pylogix2 (Daniel) not pylogix. Daniel has a rogue fork, we tried working with him on a PR and he decided to ignore all communication.
> 
> So in the future if you want to make more PRs please fork this repo or add this repo as upstream to keep up with the latest changes.

Oof, good eye.  The gift that keeps on giving.

**Comment by TheFern2** [comment]
Yeah, it sucks that you can't control which forks can submit PRs or maybe you can I dunno. Is clearly he wanted to go his own route so he shouldn't made a fork. Because PRs come to the original repo.

**Comment by dmroeder** [comment]
It appears that @PhilippHaefele forked pylogix2, then brought it up to be closer in line with pylogix.

**Comment by TheFern2** [comment]
> It appears that @PhilippHaefele forked pylogix2, then brought it up to be closer in line with pylogix.  

yeah I saw version was the same in init file. As long as there are no conflicts is fine. PR is good to go though.

**Comment by PhilippHaefele** [comment]
Yep i locally have the right repo checked out, branched from the right master and everything seems to line up ok in my branch as @TheFern2 mentioned.

The problem is, that i cannot create a fork of pylogix and pylogix2, as GitHub forbids to fork a repo twice (pylogix & pylogix2 are fork-linked and therefore are the "same" base repo for GitHub).

I'm literally just doing the same change for pylogix2 and it just happened that i forked pylogix2 first.

Sorry should habe mentioned that.

**Comment by dmroeder** [comment]
@PhilippHaefele, Line 1394 is still a problem.

**Comment by dmroeder** [comment]
That's what I did when testing it locally

**Comment by TheFern2** [comment]
yeah that line was most likely auto generated and had a unicode decoding issue, that's why I recommend to use ascii 65-122 letters.

**Comment by PhilippHaefele** [comment]
Oh sorry forgot them in my replacing logic.

Will try to change it tomorrow

**Comment by PhilippHaefele** [comment]
Just pushed a fixed version

**Comment by PhilippHaefele** [comment]
Thanks, happy to help improving this python package

**Pull request merged**
