### PR TITLE
Optional updates to 81_simple_gui.py file

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
## Short description of change
Allow displaying values in multi-line (wrapped) when necessary and other misc updates

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?
- Redesign GUI to allow showing multi-line wrapped values when necessary
- Added a header for the Log file (Date/Time plus names of all the individual tags being read)
- Added changing background color of the update buttons depending on the enable/disable state
- Added a new 'Boolean Display' checkbox, to switch displaying boolean values from True:False to 1:0
- Updated some code for better error handling, updated some comments, replaced all double quotes with single

## What does it fix/add?
Some new features

## Test Configuration

- PLC Model
- PLC Firmware
- pylogix version 0.7.8
- python version 3.6.8
- OS type and version Windows 10 v2004

### CODE REVIEW

**Comment by TheFern2** [comment]
Hey @GitHubDragonFly great additions, this is coming along. On the boolean display toggle, I am not seeing any changes, it always shows as true/false.

**Comment by GitHubDragonFly** [comment]
You are correct. I had it setup for bool arrays only. It is fixed now.

**Comment by GitHubDragonFly** [comment]
There is one more thing that can be updated, Serial Number of the discovered devices.
It currently shows as hex string and you can possibly update it yourself to look like this:

lbDevices.insert(i * 12 + 9, 'Serial: ' + str(int(device.SerialNumber, 0)))

You would save me a trouble of submitting yet another PR.

**Comment by GitHubDragonFly** [comment]
If you do fix showing the Serial Number in the library itself, then it will be available everywhere.

**Comment by TheFern2** [comment]
> If you do fix showing the Serial Number in the library itself, then it will be available everywhere.

Done fixed on master, good catch!

**Pull request merged**
