### PR TITLE
Multiple enhancements

### PR DESCRIPTION
**Pull request by jprogin-i3**
# Short description of changes

- Recursive tags extraction from structured types and array
- Multiple tags reading enhancements
- Several minor fixes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **docs/CONTRIBUTING.md** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Note

Unfortunately, I don't have the control of the PLC I'm connecting to and I cannot run the tests (can't upload program). Could you check by your side, please?

## What does it fix/add?

The GetTagList has been enhanced to browse the structured type to generate the full tag list.

When reading multiple tags there were no check of the request size, producing errors when to much tags where requested. This fix monitors the size of the request block and split into several requests when needed.

### CODE REVIEW

**Comment by kodaman2** [comment]
@jprogin thanks for the re PR 👍 

> Unfortunately, I don't have the control of the PLC I'm connecting to and I cannot run the tests (can't upload program). Could you check by your side, please?

I think we can manage that, what sort of new tests do you have in mind?

- Could you give an example of when did the GetTagList function failed due to request size?
   - Type of tag(s), size
   - How many tags
  - Other useful information

- Given that scenario, how many more tests do you think will be necessary to test this feature?

**Comment by jprogin** [comment]
Dear Fernando,

GetTagList does not fail; but now it browse into structures and arrays to build the whole tag list.

The Read was failing when the number of tags requested exceeds the 512 bytes of the request. It does not depends only on the number of tags, but also on their name length and their types. The threshold is not that clear... But now, it monitors the request length and can splits the operation into several requests and reassemble the result into a single array.

Jacques

**Comment by kodaman2** [comment]
I have some good and bad news for you. I just ran the existing unittests which test current functionality  for python 2.7 and > 3, your changes have broken 2.7. Python 3.4 passed, but we still new to add new tests to test your changes.

image

This is a dump of the errors on python 2.7:

```
py27 run-test-pre: PYTHONHASHSEED='195'
py27 run-test: commands[0] | python 'tests\PylogixTests.py'
....EE..E....
======================================================================
ERROR: test_get_tags (__main__.PylogixTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\PylogixTests.py", line 329, in test_get_tags
    tags = comm.GetTagList()
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 146, in GetTagList
    tag_list = self._getTagList(allTags)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 600, in _getTagList
    updated_list = self._getUDT(tags)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 688, in _getUDT
    field.AccessRight = scope[1][0] & 0x03
TypeError: unsupported operand type(s) for &: 'str' and 'int'

======================================================================
ERROR: test_lgx_tag_class (__main__.PylogixTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\PylogixTests.py", line 341, in test_lgx_tag_class
    tags = comm.GetTagList()
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 146, in GetTagList
    tag_list = self._getTagList(allTags)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 600, in _getTagList
    updated_list = self._getUDT(tags)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 688, in _getUDT
    field.AccessRight = scope[1][0] & 0x03
TypeError: unsupported operand type(s) for &: 'str' and 'int'

======================================================================
ERROR: test_program_tag_list (__main__.PylogixTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\PylogixTests.py", line 369, in test_program_tag_list
    program_tags = comm.GetProgramTagList('Program:MainProgram')
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 168, in GetProgramTagList
    program_tags = self._getProgramTagList(programName)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 632, in _getProgramTagList
    updated_list = self._getUDT(tags)
  File "C:\git\pylogix\.tox\py27\lib\site-packages\pylogix\eip.py", line 688, in _getUDT
    field.AccessRight = scope[1][0] & 0x03
TypeError: unsupported operand type(s) for &: 'str' and 'int'

----------------------------------------------------------------------
Ran 13 tests in 2.827s

FAILED (errors=3)
```

**Comment by jprogin** [comment]
It should not be a big deal to make it run on 2.7; did you check? 

Jacques

**Comment by kodaman2** [comment]
> It should not be a big deal to make it run on 2.7; did you check?

The results posted are 2.7, please make sure your changes are compatible with py2.7.

**Comment by dmroeder** [comment]
@jprogin-i3 I haven't tested this, but I think the following may solve the compatibility issue:

```
 scope = unpack_from('<BB', defs[1], 1 + (i-1)*2)
 field.AccessRight = scope[1] & 0x03
 field.scope0 = scope[0]
 field.scope1 = scope[1]
```

**Comment by jprogin** [comment]
Dear Fernando,

Thanks for the great job!

Jacques

**Pull request closed without merging**
