### PR TITLE
Micropython/patch1

### PR DESCRIPTION
**Pull request by drbitboy**
## Goal is minimal changes to existing code

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?

An alternate approach to performing vendorID=>vendorNAME lookup for Micropython.

## What does it fix/add?

Remove unnecessary mess of code in pylogix/lgx_device.Device.get_vendor(vendorID) method.

## Test Configuration

- PLC Model
- PLC Firmware
- pylogix version
- python version
- OS type and version

### CODE REVIEW

**Comment by drbitboy** [comment]
FYI:  there is a new Python source file under pylogix/ named lgx_uvendors.py.

I did **_not_** convert that to a .mpy file under upylogix/; the corresponding lgx_uvendors.mpy file under upylogix/ is empty and is intended as a placeholder _**only**_.

package.json has been modified to put the contents of upylogix/vendors.txt into a file named upylogix/lgx_uvendors.py.txt, which I hope will make finding that file easier when the open(".../lgx_uvendors.py.txt") call is made.

**Comment by TheFern2** [comment]
I like the approach followed here, so my first question would be has any of this been tested on a device?

A few comments on this PR:
- I don't understand the change in package.json, you're placing vendors.txt which contains 1500 or so vendors with a py file that has a one liner. Essentially you'll have no vendors on the device.
- The path when mip is used is pylogix, not upylogix.
- os module on micropython has no `__file__` so lgx_uvendors will definitely fail on look up
- in order to make PRs for micropython please test on device before submitting the PR

**Comment by TheFern2** [comment]
For the purposes of micropython which has limited modules, please test as follow before submitting PR:

- make changes
- run build_mpy.sh
- have latest python2 and 3 on machine
- run tox unittests (this will ensure python still working as before)
- run micropython unix/port tests (I dunno how to do this on wsl but I make a comment on tests/README)
- If all this passes then test on device, everything can be tested on unix port except the discover stuff since unix/port has no network module. And network module is needed to get current device ip.
- If you commit your changes to your branch, you can then use mip and see how things are going.

**Comment by drbitboy** [comment]
>     * os module on micropython has no `__file__` so lgx_uvendors will definitely fail on look up

__file__ is not part of os; every python **_module_** has __file__ and __name__ variables, at least in the non-microcontroller (e.g. WSL/Ubuntu) micropythonenvironments.  Whether that works on a microcontroller will have to wait until I actually have one.

**Comment by drbitboy** [comment]
> I like the approach followed here, so my first question would be has any of this been tested on a device?

no, I don't have one; I have run it in the micropython repl under WSL2, which I had hoped was close to what the environment would be under a device.

Can you recommend a device?

**Comment by drbitboy** [comment]
> run build_mpy.sh (might need to make another bat file for windows)

where do I find mpy-cross?

**Comment by TheFern2** [comment]
> Can you recommend a device?

I like the esp32 with the wifi module, also the raspberry pi pico.

**Comment by drbitboy** [comment]
Either way, the .keys() should be dropped from **vendorID in vendors.keys()** as it is both slow (possibly O(N) vs O(logN)) and unnecessary.

**Pull request merged**
