### PR TITLE
Updates to 81_simple_gui.py

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
## Short description of change
Add background threads and Micro800 option

## Types of changes
Functional

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?
- Allow faster GUI startup by placing Connection on a separate thread
- Micro800 PLC selection option - not tested with an actual device
- Show pylogix version in GUI, intended for troubleshooting purposes only

## What does it fix/add?
- Better functionality for original release
- Micro800 would need to be tested against a physical device or a simulator

## Test Configuration

- PLC Model
- PLC Firmware
- pylogix version 0.7.8
- python version 3.9
- OS type and version Windows 10 version 2004

### CODE REVIEW

**Comment by TheFern2** [comment]
@GitHubDragonFly I think you might be doing a slightly out of sequence workflow.

You initial pull request was already merged https://github.com/dmroeder/pylogix/commits/master you can see that on 5f661da62be0149b5cf22dda552db34ebb88ed43 however if you look on your fork https://github.com/GitHubDragonFly/pylogix/commits/master you did not pull and that commit isn't on your fork, and then you kept working on your initial file. 

So now if you look here https://github.com/dmroeder/pylogix/pull/158/files it looks like there is no diff at all, and github/git thinks is a brand new file which it isn't.

I have the PR on my computer, and there is way too many conflicts for me to fix them manually, as I don't know if head or incoming change are the correct LOC. Every red spot is a merge conflict, because you did not pull from upstream when your initial file was merged. Anytime you work on a file or feature you need to make sure you update your fork from upstream to avoid these issues.

image

In order for this to get fix, make sure both remotes are under your local repo. origin is the default name, and upstream what I call the original repo, but it can be anything you want:

```
git remote -v
```

result:

```
~/g/pylogix  (GitHubDragonFly-master|MERGING) ❯❯❯ git remote -v
origin  git@github.com:TheFern2/pylogix.git (fetch)
origin  git@github.com:TheFern2/pylogix.git (push)
upstream        git@github.com:dmroeder/pylogix.git (fetch)
upstream        git@github.com:dmroeder/pylogix.git (push)
```

Then, on your fork master branch, this will update your fork with upstream (original repo):

```
git pull upstream master
git push origin master
```

At this time I believe you should get a warning about conflicts, and you should fix one by one manually I recommend using vscode as you get nice buttons for selecting which change to accept, then you might have to commit at the end.

**Comment by GitHubDragonFly** [comment]
That sounds like a lot of work. I will just close this PR and might eventually decide what to do with the updated file.

**Comment by TheFern2** [comment]
Exactly what I said, if you had looked on the PR before you close it, it tells you conflicts on that page too, if you want to fix them there, I've never done it through the site tbh. But normally you want that check to be green for a successful PR pull.

Merge conflicts are expected here and there and I can fix one or two conflicts, but not an entire file since I don't have a baseline for what you actually changed without doing a diff, which I shouldn't have to do. It will be a lot of work for me to do a visual manual verification what's what.

Just remember to keep your fork updated in the future, most importantly with the file your working with. Actually what I do is to keep master branch always updated with upstream. And work on features on a branch.

```
git checkout master
git pull upstream master
```

Then on your feature branch:

```
git checkout someBranch
git merge master
```

This applies to any other open source project, not just pylogix.

**Comment by GitHubDragonFly** [comment]
If only I paid attention on time.

I will try to delete and re-create the fork to see if that gets me anywhere. I am not sure how it will reflect on the pointer to the pull request for the file you already merged.

**Pull request closed without merging**
