### PR TITLE
extended forward open is working

### PR DESCRIPTION
**Pull request by aansel-plenty**
Updated _buildCIPForwardOpen() to look at a connection size parameter (self.ConnectionSize) to determine if an extended forward open is necessary. Since Allen-Bradley PLCs support forward opens of up to 4002 bytes I have limited values. The standard forward open will be used for any connection sizes less than or equal to 504 bytes per the CIP specification.

### CODE REVIEW

**Comment by dmroeder** [comment]
First of all, thanks for the effort.  I had considered the large forward open a while back but shy'd away since not all controller support it.  Having the standard connection size with a larger one as an option should be great.

If you don't mind making a few changes, I'll pull this.  Keep in mind that my suggestions will sound hypocritical since I've done some of these things too.  I have a list of things I'll be cleaning up, hopefully sooner rather than later...

1) I'm moving away from in line comments
2) I'm not a fan of extra spaces to align variable assignment. (ex. this      = that)
3) I wouldn't make your new variables part of the class (ex. ConnectionType instead of self.ConnectionType)

Down the road, I may change a it up a little, I plan on moving closer to PEP8 standards.

**Comment by aansel-plenty** [comment]
I am a super novice software programmer so thanks for the advice. I'll try and make the changes when I get some time at work. Though feel free to make the changes as well if it is possible.

**Comment by dmroeder** [comment]
This has been a learning experience for myself as well so I know where you are coming from.

**Comment by dmroeder** [comment]
So I've pulled this into my local repo and have been testing.  There is something up when using larger packet sizes that I have to work through before I can push this out. It isn't necessarily related to these changes but most likely how I'm dealing with receiving the reply.

**Pull request merged**
