### PR TITLE
[WIP] Documentation

### PR DESCRIPTION
**Pull request by kodaman2**
I have been sitting on this branch for a while. I'll make the PR otherwise I will procrastinate more.
Still a WIP, but I'll merge when I am done. Let me know what you think. I still have to update with latest changes too.

It contains the following:

- Starter Guides
- Templates for Issues and pull request (please review these, and lemme know what to add/remove)
- Contributing doc
- Documentation doc which eventually will have the functions api kinda like a javadoc if you will.

### CODE REVIEW

**Comment by tobiasht** [comment]
Looks awesome, great work man!

**Comment by kodaman2** [comment]
@tobiasht Thanks!

**Comment by dmroeder** [comment]
Looks really good man, a lot of nice work there!  I think your templates and such capture this but I'll just think out loud here:

When I make changes, I have in the back of my mind all of the pitfalls that I've ran into over the years.  Well, at least all of the ones I can remember!  So when I'm testing major changes, I'm thinking of large arrays, BOOL arrays, large packets, mixed tags in lists, etc.  Of course the automated testing helps with this.  Once I get the sim working, I'll be able to test more than I can easily test with my controller.  I guess I say this only to reiterate testing more that just the thing that is being worked on.  Also to to spell out what exactly was tested and just as importantly, what wasn't.

The routing PR comes to mind.  I don't have the means to test this easily, which makes me hesitant to pull it.  I don't want to end up attempting to support a feature that is difficult for me to test.  So for that PR, knowing what exactly was tested and how it was tested would give me more piece of mind.   I'm not telling you anything new :)

One thing that will need to be changed is updating the examples to reflect the newer Response class.

**Comment by kodaman2** [comment]
The routing PR is what made me write all this documentation in the first place lol. I fully agree and that is the reason for tox combined with unit testing, but we have to add more to the initial unit tests. Yes, every PR should run tox, and pass 100% current tests, plus the new features added of course.

If a PR submitter is not good with unit test I guess we can step in too, and then whoever is merging the PR, ideally we should run just to double check nothing was broken and that the tests % reported was indeed true.

I guess I should add a Code of Conduct somewhere in there as well so PR submitters to see the expectations, which should include good communication, testing, clean code, respect, etc.

> One thing that will need to be changed is updating the examples to reflect the newer Response class.

Yes, this commit was done well before the Response class, in retrospect, I will probably separate the PR/Issue templates on another PR so people can start using those right away while the docs are being written.

> Also to to spell out what exactly was tested and just as importantly, what wasn't.

I plan on adding some of the stuff I wrote on the Tests/README.md to the contributions.md to emphasize overall testing, and when to decide if a PR is just worth too much hassle from the maintainers perspective.

**Pull request merged**
