### PR TITLE
BUG Fix for logging values to a text file

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
## Short description of change
BUG Fix

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?
- This fixes a BUG when logging values to a text file (which was introduced with the latest new feature of 81_simple_gui.py file) 
- Some other changes to ease importing the log into Excel (including array values). This has to be done by a user, either change the extension ".txt" to ".csv" in the code or just rename the log file once created.
- Removed unused variable

## What does it fix/add?
Fixes a BUG that caused the log file entries be scattered.

## Test Configuration

- PLC Model
- PLC Firmware
- pylogix version 0.7.10
- python version 2.7.18 and 3.6.8
- OS type and version Windows 10 v2004

### CODE REVIEW

**Comment by TheFern2** [comment]
What is the reason to create a csv data file, and having the extension as txt? Would it make sense to just create a csv from the start?

Not sure if this is what you intended but header row now only has date column:

```
Date / Time, 
2021-03-30/06:47:33.725992, True, 545437493
2021-03-30/06:47:34.231560, True, 545437493
2021-03-30/06:47:34.739083, True, 545437493
2021-03-30/06:47:35.244650, True, 545437493
```

**Comment by GitHubDragonFly** [comment]
The txt extension is generally acceptable for everybody. Some users might not be using csv at all and could possibly get confused with the extension.

The log header should be fixed now.

**Comment by GitHubDragonFly** [comment]
Logging values only makes sense for the initial list of tags.

If the tags are changed then the current log file should be renamed or moved to a different location.
Otherwise, the newly logged values will not match the existing header.

**Comment by TheFern2** [comment]
Makes, sense. Thanks for the bug fix.

**Pull request merged**
