### PR TITLE
Added support for custom CIP routing path for the GetModuleProperties…

### PR DESCRIPTION
**Pull request by daniel-leicht**
… function.

This gives the developer the option to access nested backplanes/buses (Such as CompactBus, DeviceNet, etc...)

Updated the README with an example.

### CODE REVIEW

**Comment by dmroeder** [comment]
Thanks for the contribution Daniel, I'll take a look here soon, I'm going to be away for a few days.  A few quick thoughts:

I haven't put this project on pypi yet, I'm going to if I get time while I'm away, or when I return.  
Have you tested this with both python2 and python3?
The setup file in my repo should still point to my repo.

**Comment by kodaman2** [comment]
Hi Daniel thanks for the PR. I am currently working on unit testing the whole library.

A couple questions, excuse my ignorance on custom cip paths, just trying to get my head around this to make sure is properly tested.

Can you include descriptions on what those two tuples are, or is it as simple rack/slot?

If I wanted to test this, I would just need a second backplane and another plc in any slot, correct?

**Comment by kodaman2** [comment]
I've added #72 PR for unittests. Once that PR is checked and hopefully approved, you will have to add some tests for this PR.

**Comment by daniel-leicht** [comment]
> Hi Daniel thanks for the PR. I am currently working on unit testing the whole library.
> 
> A couple questions, excuse my ignorance on custom cip paths, just trying to get my head around this to make sure is properly tested.
> 
> Can you include descriptions on what those two tuples are, or is it as simple rack/slot?
> 
> If I wanted to test this, I would just need a second backplane and another plc in any slot, correct?

Hi @kodaman2 

Yes, not just a backplane, but any bus or other routeable PLC via one of the ports in the module.

One such example is common in CompactLogix PLCs, the CPU module has a "Backplane" port in one side and a "CompactBus" port in the other side (where the I/O modules reside).

If you want to reach the I/O module through an ENBT, you need to route the PDU via the "CompactBus" port of the CPU module.

**Comment by kodaman2** [comment]
@dmroeder I assume this PR can be closed?

**Pull request closed without merging**
