### PR TITLE
Optional update including some more error checking

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
## Short description of change
- Mainly enclosing background threads functions with try-except-pass

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **docs/CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read **tests/README.md**.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## What is the change?
- Just some more error checking

## What does it fix/add?
- Just some more error checking

## Test Configuration

- PLC Model
- PLC Firmware
- pylogix version 0.7.11
- python version 3.6.8
- OS type and version Windows 10 v2004

### CODE REVIEW

**Comment by dmroeder** [comment]
Do you plan on pushing more updates to this @GitHubDragonFly?   The examples were really meant for simple, clear usages, for new people.  As opposed to full fledged programs that need maintenance.  Though I do think this is a good showing of what can be done.

I have been waiting to see if more changes were going to be added before pulling.

**Comment by GitHubDragonFly** [comment]
Yes, there is one more thing I want to update, which is starting fresh logging of the values every time the tags are changed and the logging is enabled. This is already a part of the PR which is currently in the pycomm3 repository so I just need to move it to pylogix file.

Give me a few days and once you see the next commit then you can pull it in.

**Comment by dmroeder** [comment]
Sounds good, I'll hang tight.

**Comment by GitHubDragonFly** [comment]
I think that I'm done with updating this particular file.
It is intended to showcase the use of pylogix and be used for troubleshooting.

Didn't notice any bugs in my testing but users can report it if they find any.

**Pull request merged**
